### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by ondblclick** [iLib-js/iLib#178]
Looks like `Example of Using iLib Under NodeJS` from the readme is not working:

`index.js:`
```
var DateFactory = require("ilib/lib/DateFactory.js");
var DateFmt = require("ilib/lib/DateFmt.js");

var d = DateFactory();
var f = new DateFmt({
    locale: "de-DE",
    type: "datetime",
    length: "long",
    timezone: "Europe/Berlin"
});

f.format(d);
```
and running it as 

```
node index.js
```

throws:
```
TypeError: Cannot read property 'onLoad' of undefined
```

Anything else I should import/pass to the config object for a DateFmt?

**Comment by ehoogerbeets** [comment]
Hi Bohdan, thanks for using ilib. Which version are you using? In 14.1.2, it works:

```
% node
> var DateFactory = require("ilib/lib/DateFactory.js");
undefined
> var DateFmt = require("ilib/lib/DateFmt.js");
undefined
> var d = DateFactory();
undefined
> var f = new DateFmt({
...     locale: "de-DE",
...     type: "datetime",
...     length: "long",
...     timezone: "Europe/Berlin"
... });
undefined
> f.format(d);
'23. April 2019 um 19:56'
> var ilib = require("ilib");
undefined
> ilib.getVersion()
'14.1.2'
```

I should actually promote 14.X to be the latest, as it is pretty stable now. It currently has the "experimental" tag in npm, and the "latest" is still pointing at 13.3.1.

Let me know what your version is and I'll see if I can trace it down. Possibly just a problem with the docs... in 13.X and earlier, you had to do `var ilib = require("ilib");` first before any other requires in order to install the correct locale data loader for your platform. I resolved that problem in 14.X by auto-detecting the platform first and then requiring the right loader.

**Comment by ondblclick** [comment]
@ehoogerbeets ah, ok, thanks. Yes, it's 13.3.1 exactly what was installed through `npm i ilib`. Adding the `var ilib = require("ilib");` made it work. Thanks!
